### ISSUE TITLE
As a user I would like to be able to track more than one skill.

### ISSUE THREAD

**Issue by MattRueter** [chingu-voyages/v43-tier2-team-21#17]
e.g. I'm learning the piano, Swedish, and want to get fit.
I'd like to set each of these up separately as things to track.

**Comment by MattRueter** [comment]
- [ ] user can see information related to individual skill.
- [ ] user can see information related to all skills. 

### Sessions
- [ ] information specific to number of completed sessions is clearly displayed.
- [ ] information specific to number of session-goals is clearly displayed.

### Time
- [ ] information specific to time spent on skills is clearly displayed.
- [ ] information specific to time set as goal is clearly displayed.
